import { LastPriceAnimationMode } from "lightweight-charts";
import { DOWN_COLOR, UP_COLOR } from "./trade-theme";

// Chart theme
export var CHART_THEME = {
	backgroundColor: "#191919",
	textColor: "#ffffff",
	fontSize: 12,
	fontFamily: "Arial",
	vertGridVisible: true,
	horzGridVisible: true,
	vertGridColor: "rgba(197, 203, 206, 0.5)",
	horzGridColor: "rgba(197, 203, 206, 0.5)",
	timeVisible: true,
	timeSecondsVisible: false,
	timeScaleBorderVisible: true,
	timeScaleBorderColor: "#191919",
	timeScaleRightOffset: 10,
	priceScaleMode: "normal",
	autoScale: true,
	priceScaleBorderVisible: true,
	priceScaleBorderColor: "#191919",
	priceScalePosition: "right",
	lastPriceAnimationMode: LastPriceAnimationMode.Continuous,
	crosshairMode: "normal",
	crosshairVertColor: "#191919",
	crosshairHorzColor: "#191919",
	crosshairVertStyle: 0,
	crosshairHorzStyle: 0,
	upColor: UP_COLOR,
	downColor: DOWN_COLOR,
	borderVisible: false,
	borderUpColor: "#191919",
	borderDownColor: "#191919",
	wickUpColor: UP_COLOR,
	wickDownColor: DOWN_COLOR,
	lineColor: "#191919",
	lineWidth: 2,
	lineStyle: 0,
	lineType: 0,
	topColor: "#191919",
	bottomColor: "#191919",
	watermarkText: "",
	watermarkColor: "#191919",
	watermarkFontSize: 12,
	watermarkVisible: false,
};
